version: '3.8'

services:
  nginx:
    image: nginx:1.19.10
    container_name: nginx
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../html:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - php
      - mysql

  php:
    build: ./
    container_name: php-fpm
    volumes:
      - ../../html:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    secrets:
      - mysql_root_password
      - mysql_db_password
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    container_name: phpmyadmin
    networks:
      - backend
    depends_on:
      - mysql
    secrets:
      - mysql_root_password

volumes:
  mysql-data:

networks:
  frontend:
  backend:

secrets:
  mysql_root_password:
    file: ../../secrets/mysql_root_password.txt
  mysql_db_password:
    file: ../../secrets/mysql_db_password.txt